### ISSUE TITLE
[Bug] Crash when displaying Mana and Artifice Runescribing Recipe item

### ISSUE THREAD

**Issue by Mrbysco** [shiroroku/LootBeams#4]
## Client info
* Minecraft Version: 1.16.5
* Forge Version: 1.16.5-forge-36.2.0
* Mod Version: 1.16.5-release-aug2021
* Java Version: 1.8.0_232

## Issue Description
A crash occurs when you drop a Runescribing Recipe item and LootBeams tries to render the name/tooltip.
(Reporting on behalf of a friend)

## Reproduce Steps 
Drop a Mana and Artifice Runescribing Recipe on the floor.

## Additional Information
[Pastebin of Crashlog](https://pastebin.com/YCWS81eh)

**Comment by shiroroku** [comment]
from my testing this seems to be an issue with mana and artifice failing to load a recipe on its tooltip. it's hard to figure out what's really going on since mana and artifice isn't open source. i think the only fix for now is to blacklist the mod or item in lootbeam's config. you can also share this to the mod dev in hopes they can fix it.

`blacklist = ["mana-and-artifice"]` (disables lootbeams for all of mana and artifice's items)
or
`blacklist = ["mana-and-artifice:runescribing_recipe_paper"]` (disables lootbeams just for that item)

on the code side i think maybe they don't do a null check for `PlayerEntity` in `getTooltipLines(@Nullable PlayerEntity, ITooltipFlag)` since lootbeams passes in a null PlayerEntity. but i could be wrong.
